name: quran_widget_flutter
description: quran_widget_flutter.
version: 0.0.1
homepage: https://github.com/fritill-team/quran_flutter_wigdget_package

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.0.2
  dio: ^4.0.0
  dio_cache_interceptor: ^3.0.1
  floor: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_downloader: ^1.7.2
  path_provider: ^2.0.9
  sqflite: ^2.0.2

dev_dependencies:
  build_runner: ^2.1.2
  floor_generator: ^1.2.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter


flutter:

  assets:
    - assets/img/
    - assets/fonts/

  
  fonts:
    - family: HafsSmart
      fonts:
        - asset: assets/fonts/hafs_smart_08.ttf 

    - family: QuranKarim
      fonts:
        - asset: assets/fonts/quran_karim.ttf

    - family: Bazzi1
      fonts:
        - asset: assets/fonts/uthmanic_bazzi1_ver07.ttf

    - family: Doori
      fonts:
        - asset: assets/fonts/uthmanic_doori1ver09.ttf

    - family: Hafs17
      fonts:
        - asset: assets/fonts/uthmanic_hafs1_ver17.ttf 
